### ISSUE TITLE
Review Rahul Meeting

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/memorization-app#2] opened 2022-09-12 09:08 UTC

**Comment by kushal-ti** [comment] 2022-09-13 06:51
If work on an issue is done 
1. you should have recorded what you accomplished in it (tangible results, in this case, the intention for reviewing the meet and what learnings you gained from it )
2. The issue should be closed 
3. There should have been an issue assignee, which can still be added, since the issue isn't closed yet

**Comment by gao-ti** [comment] 2022-09-13 08:15
Main idea: commercial 

* Rahul wants a solution for the client.
* No scope. No specified method. No spec/expectation on the end product.

* Memory techniques https://artofmemory.com/wiki/Main_Page/

**Comment by kushal-ti** [comment] 2022-09-13 10:19
I'm closing this for now, but we will discuss this more later

**Closed by kushal-ti** 2022-09-13 10:19 UTC
